import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Button";

import { Card1,  Card2, Card3,
   Card4, Card5 } from "../components/card.js";
import { useMoralis } from "react-moralis";





const supportedChains = ["31337", "4"];





export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  

  return (
    
    
    
    <div className={styles.container}>
      
     
       
      <Head>
        <title>Presenting Capsules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    

      
      <div id ="front-card-1">
      <Card1/> 
      
            
      
      </div>
      <div id = "front-card-2">
       <Card2/> </div>
       <div id = "front-card-3">
       <Card3/> </div>
      
       <div id = "front-card-5">
       <Card5/> </div>
    </div>

  
      
    

    

    
  );
  
}

